# -*- coding: utf-8 -*-
"""Vendor Sales Analysis_ Precious Nwachukwu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOiW2EeJRpm-7i_SunUFRao4bAzulopH

# 🛒 Nigerian Provisions Store Vendor Sales Analysis

---


**Analyst:** Precious Nwachukwu | Data Analyst  
**Tool:** Python (pandas, numpy, matplotlib)  
**Dataset:** 500 sales transactions | Jan–Dec 2024  
**Store type:** General provisions store, Abuja, Nigeria

### Business Questions:
1. Which product categories generate the most revenue and profit?
2. What are the top-performing products?
3. How does sales performance vary by month and day of week?
4. Which payment methods do customers prefer?
5. What is the impact of discounting on margins?
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

plt.rcParams['figure.figsize'] = (12, 5)
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.3

print("✅ Libraries loaded. Ready to go.")

import random
from datetime import datetime, timedelta

random.seed(42)
np.random.seed(42)

products = [
    ("Dangote Rice 5kg", "Grains & Staples", 3800, 4500, 3),
    ("Mama Gold Rice 5kg", "Grains & Staples", 3600, 4200, 4),
    ("Semovita 1kg", "Grains & Staples", 900, 1100, 5),
    ("Garri (White) 2kg", "Grains & Staples", 1200, 1500, 6),
    ("Garri (Yellow) 2kg", "Grains & Staples", 1300, 1600, 4),
    ("Beans (Oloyin) 2kg", "Grains & Staples", 2200, 2700, 3),
    ("Spaghetti (Golden Penny)", "Grains & Staples", 500, 650, 8),
    ("Indomie Noodles (Chicken) x5", "Grains & Staples", 650, 800, 12),
    ("Indomie Noodles (Onion Chicken) x5", "Grains & Staples", 650, 800, 10),
    ("Honeywell Flour 1kg", "Grains & Staples", 800, 980, 4),
    ("Kings Vegetable Oil 1L", "Oils & Condiments", 1800, 2200, 5),
    ("Devon King's Palm Oil 1L", "Oils & Condiments", 1500, 1900, 6),
    ("Frytol Sunflower Oil 1L", "Oils & Condiments", 1900, 2300, 3),
    ("Maggi Cubes x10", "Oils & Condiments", 400, 500, 15),
    ("Knorr Cubes x10", "Oils & Condiments", 420, 520, 12),
    ("Benny Tomato Paste 400g", "Oils & Condiments", 600, 750, 8),
    ("Tatashe Powder 100g", "Oils & Condiments", 350, 450, 6),
    ("Iodized Table Salt 500g", "Oils & Condiments", 250, 350, 10),
    ("Cameroon Pepper 100g", "Oils & Condiments", 400, 550, 7),
    ("Milo 400g", "Beverages", 2200, 2700, 5),
    ("Ovaltine 400g", "Beverages", 2000, 2500, 4),
    ("Nescafe Classic 100g", "Beverages", 2800, 3400, 3),
    ("Lipton Yellow Label 50 bags", "Beverages", 600, 750, 8),
    ("Peak Milk Powder 400g", "Beverages", 2600, 3100, 5),
    ("Cowbell Milk Powder 360g", "Beverages", 2200, 2700, 6),
    ("Bournvita 400g", "Beverages", 2300, 2800, 4),
    ("Lacasera Apple Drink x6", "Beverages", 1800, 2200, 4),
    ("Chivita Juice 1L", "Beverages", 900, 1100, 5),
    ("Eva Water 75cl x12", "Beverages", 1200, 1500, 7),
    ("Omo Detergent 500g", "Household & Cleaning", 900, 1100, 6),
    ("Ariel Detergent 500g", "Household & Cleaning", 1100, 1350, 5),
    ("Izal Disinfectant 750ml", "Household & Cleaning", 700, 900, 4),
    ("Dettol Liquid Soap 250ml", "Household & Cleaning", 800, 1000, 6),
    ("Harpic Toilet Cleaner 500ml", "Household & Cleaning", 1100, 1400, 3),
    ("Snuggle Fabric Softener 1L", "Household & Cleaning", 1300, 1600, 3),
    ("Canoe Bar Soap x6", "Household & Cleaning", 600, 750, 8),
    ("Morning Fresh Dish Soap 500ml", "Household & Cleaning", 850, 1050, 5),
    ("Close-Up Toothpaste 150ml", "Personal Care", 700, 900, 7),
    ("Oral-B Toothbrush (2pk)", "Personal Care", 600, 800, 5),
    ("Vaseline Body Lotion 400ml", "Personal Care", 1500, 1900, 5),
    ("Pears Baby Lotion 200ml", "Personal Care", 1200, 1500, 4),
    ("Dove Soap 90g", "Personal Care", 700, 900, 6),
    ("Fa Roll-On Deodorant 50ml", "Personal Care", 900, 1150, 5),
    ("Always Sanitary Pads (10pk)", "Personal Care", 800, 1050, 6),
    ("Pampers Diapers Size 3 x16", "Personal Care", 2800, 3400, 3),
    ("Cabin Biscuits 200g", "Snacks & Confectionery", 450, 600, 10),
    ("Digestive Biscuits 200g", "Snacks & Confectionery", 500, 650, 8),
    ("Kirks Plantain Chips 100g", "Snacks & Confectionery", 350, 450, 9),
    ("Gala Sausage Roll", "Snacks & Confectionery", 250, 350, 20),
    ("Mr. Biggs Meat Pie", "Snacks & Confectionery", 400, 550, 12),
    ("Nestle Kitkat 4-finger", "Snacks & Confectionery", 500, 650, 7),
    ("Choco Milo Cubes x10", "Snacks & Confectionery", 300, 400, 15),
    ("Tom Tom Sweets x20", "Snacks & Confectionery", 200, 280, 18),
]

start_date = datetime(2024, 1, 1)
rows = []
transaction_id = 1000

for _ in range(500):
    product = random.choice(products)
    name, category, cost, price, avg_qty = product
    date = start_date + timedelta(days=random.randint(0, 364))
    month = date.month
    weekday = date.weekday()
    qty_multiplier = 1.0
    if weekday >= 4:
        qty_multiplier *= 1.4
    if date.day >= 25 or date.day <= 5:
        qty_multiplier *= 1.3
    if month in [11, 12]:
        qty_multiplier *= 1.5
    if month in [1, 2]:
        qty_multiplier *= 0.75
    qty = max(1, int(np.random.poisson(avg_qty * qty_multiplier)))
    discount_pct = random.choices([0, 5, 10], weights=[70, 20, 10])[0]
    actual_price = round(price * (1 - discount_pct / 100), -1)
    revenue = qty * actual_price
    total_cost = qty * cost
    profit = revenue - total_cost
    margin = round((profit / revenue) * 100, 1) if revenue > 0 else 0
    payment_method = random.choices(["Cash", "Transfer", "POS"], weights=[55, 30, 15])[0]
    rows.append({
        "transaction_id": f"TXN{transaction_id}",
        "date": date.strftime("%Y-%m-%d"),
        "month": date.strftime("%B"),
        "day_of_week": date.strftime("%A"),
        "product_name": name,
        "category": category,
        "quantity_sold": qty,
        "unit_cost_ngn": cost,
        "unit_price_ngn": actual_price,
        "discount_pct": discount_pct,
        "total_revenue_ngn": revenue,
        "total_cost_ngn": total_cost,
        "profit_ngn": profit,
        "profit_margin_pct": margin,
        "payment_method": payment_method,
    })
    transaction_id += 1

df = pd.DataFrame(rows).sort_values("date").reset_index(drop=True)
df['date'] = pd.to_datetime(df['date'])
print(f"✅ Dataset ready: {df.shape[0]} rows × {df.shape[1]} columns")
print(df.head(3))

print("=" * 55)
print("   NIGERIAN PROVISIONS STORE — 2024 ANNUAL SUMMARY")
print("=" * 55)
print(f"  Total Transactions:    {len(df):,}")
print(f"  Date Range:            {df['date'].min().date()} to {df['date'].max().date()}")
print(f"  Unique Products:       {df['product_name'].nunique()}")
print(f"  Product Categories:    {df['category'].nunique()}")
print(f"  Total Revenue:         N{df['total_revenue_ngn'].sum():,.0f}")
print(f"  Total Profit:          N{df['profit_ngn'].sum():,.0f}")
print(f"  Avg Profit Margin:     {df['profit_margin_pct'].mean():.1f}%")
print(f"  Avg Transaction Value: N{df['total_revenue_ngn'].mean():,.0f}")
print("=" * 55)
print("\nMissing Values:")
print(df.isnull().sum())

import matplotlib.ticker as mticker

category_summary = df.groupby("category").agg(
    total_revenue=("total_revenue_ngn", "sum"),
    total_profit=("profit_ngn", "sum"),
    avg_margin=("profit_margin_pct", "mean"),
    transactions=("transaction_id", "count")
).sort_values("total_revenue", ascending=False).reset_index()

print("📂 Revenue & Profit by Category:")
print(category_summary.to_string(index=False))

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle("Revenue & Profit by Product Category\nNigerian Provisions Store — 2024", fontsize=14, fontweight='bold')

colors = ['#2E7D32', '#388E3C', '#43A047', '#66BB6A', '#81C784', '#A5D6A7']

axes[0].barh(category_summary['category'], category_summary['total_revenue'] / 1e6, color=colors)
axes[0].set_xlabel("Revenue (₦ Millions)")
axes[0].set_title("Total Revenue by Category")
for i, v in enumerate(category_summary['total_revenue'] / 1e6):
    axes[0].text(v + 0.02, i, f'₦{v:.2f}M', va='center', fontsize=9)

axes[1].barh(category_summary['category'], category_summary['avg_margin'], color='#1565C0')
axes[1].set_xlabel("Avg Profit Margin (%)")
axes[1].set_title("Average Profit Margin by Category")
for i, v in enumerate(category_summary['avg_margin']):
    axes[1].text(v + 0.1, i, f'{v:.1f}%', va='center', fontsize=9)

plt.tight_layout()
plt.show()

top_products = df.groupby("product_name").agg(
    total_revenue=("total_revenue_ngn", "sum"),
    total_profit=("profit_ngn", "sum"),
    units_sold=("quantity_sold", "sum"),
    avg_margin=("profit_margin_pct", "mean")
).sort_values("total_revenue", ascending=False).head(10).reset_index()

print("🏆 Top 10 Products by Revenue:")
print(top_products.to_string(index=False))

fig, ax = plt.subplots(figsize=(12, 7))
bars = ax.barh(top_products['product_name'][::-1],
               top_products['total_revenue'][::-1] / 1000,
               color='#1565C0')
ax.set_xlabel("Revenue (₦ Thousands)")
ax.set_title("Top 10 Products by Total Revenue\nNigerian Provisions Store — 2024", fontweight='bold')
for bar, val in zip(bars, top_products['total_revenue'][::-1] / 1000):
    ax.text(val + 1, bar.get_y() + bar.get_height() / 2,
            f'₦{val:.0f}K', va='center', fontsize=9)
plt.tight_layout()
plt.show()

month_order = ["January","February","March","April","May","June",
               "July","August","September","October","November","December"]

monthly = df.groupby("month").agg(
    revenue=("total_revenue_ngn", "sum"),
    profit=("profit_ngn", "sum"),
    transactions=("transaction_id", "count")
).reindex(month_order).reset_index()

fig, ax = plt.subplots(figsize=(13, 6))
ax.plot(monthly['month'], monthly['revenue'] / 1000, marker='o',
        linewidth=2.5, color='#1565C0', label='Revenue')
ax.plot(monthly['month'], monthly['profit'] / 1000, marker='s',
        linewidth=2.5, color='#2E7D32', linestyle='--', label='Profit')
ax.fill_between(monthly['month'], monthly['revenue'] / 1000, alpha=0.1, color='#1565C0')
ax.set_ylabel("Amount (₦ Thousands)")
ax.set_title("Monthly Revenue & Profit Trend\nNigerian Provisions Store — 2024", fontweight='bold')
ax.legend()
plt.xticks(rotation=45)
peak_month = monthly.loc[monthly['revenue'].idxmax()]
ax.annotate(f"Peak: ₦{peak_month['revenue']/1000:.0f}K",
            xy=(peak_month['month'], peak_month['revenue']/1000),
            xytext=(10, 15), textcoords='offset points',
            arrowprops=dict(arrowstyle='->', color='red'), fontsize=9, color='red')
plt.tight_layout()
plt.show()

day_order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

daily = df.groupby("day_of_week").agg(
    revenue=("total_revenue_ngn", "sum"),
    transactions=("transaction_id", "count")
).reindex(day_order).reset_index()

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle("Sales Activity by Day of Week\nNigerian Provisions Store — 2024", fontsize=13, fontweight='bold')

day_colors = ['#90CAF9','#90CAF9','#90CAF9','#90CAF9','#1565C0','#1565C0','#1565C0']
axes[0].bar(daily['day_of_week'], daily['revenue'] / 1000, color=day_colors)
axes[0].set_ylabel("Revenue (₦ Thousands)")
axes[0].set_title("Revenue by Day")
axes[0].tick_params(axis='x', rotation=40)

axes[1].bar(daily['day_of_week'], daily['transactions'], color=day_colors)
axes[1].set_ylabel("Number of Transactions")
axes[1].set_title("Transactions by Day")
axes[1].tick_params(axis='x', rotation=40)

plt.tight_layout()
plt.show()

payment = df.groupby("payment_method").agg(
    transactions=("transaction_id", "count"),
    revenue=("total_revenue_ngn", "sum")
).reset_index()

fig, axes = plt.subplots(1, 2, figsize=(11, 5))
fig.suptitle("Payment Method Analysis\nNigerian Provisions Store — 2024", fontsize=13, fontweight='bold')

pie_colors = ['#1565C0', '#2E7D32', '#F57F17']
axes[0].pie(payment['transactions'], labels=payment['payment_method'],
            autopct='%1.1f%%', colors=pie_colors, startangle=90)
axes[0].set_title("By Number of Transactions")

axes[1].pie(payment['revenue'], labels=payment['payment_method'],
            autopct='%1.1f%%', colors=pie_colors, startangle=90)
axes[1].set_title("By Revenue Value")

plt.tight_layout()
plt.show()

discount_analysis = df.groupby("discount_pct").agg(
    avg_margin=("profit_margin_pct", "mean"),
    transactions=("transaction_id", "count"),
    total_revenue=("total_revenue_ngn", "sum")
).reset_index()

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(
    discount_analysis['discount_pct'].astype(str).apply(lambda x: f"{x}% Discount"),
    discount_analysis['avg_margin'],
    color=['#2E7D32', '#F57F17', '#C62828']
)
ax.set_ylabel("Average Profit Margin (%)")
ax.set_title("Effect of Discount on Profit Margin\nNigerian Provisions Store — 2024", fontweight='bold')
for bar, val in zip(bars, discount_analysis['avg_margin']):
    ax.text(bar.get_x() + bar.get_width() / 2, val + 0.2,
            f'{val:.1f}%', ha='center', fontsize=11, fontweight='bold')
plt.tight_layout()
plt.show()

best_cat = category_summary.iloc[0]
best_margin_cat = category_summary.sort_values("avg_margin", ascending=False).iloc[0]
peak_m = monthly.loc[monthly['revenue'].idxmax()]
top_prod = top_products.iloc[0]
top_pay = payment.sort_values("transactions", ascending=False).iloc[0]
cash_pct = int(payment[payment.payment_method=='Cash']['transactions'].values[0] / len(df) * 100)

print("=" * 60)
print("   KEY INSIGHTS -- 2024 ANNUAL SALES ANALYSIS")
print("=" * 60)
print(f"\n  Revenue Leader:     {best_cat['category']} (N{best_cat['total_revenue']:,.0f})")
print(f"  Highest Margin Cat: {best_margin_cat['category']} ({best_margin_cat['avg_margin']:.1f}% avg)")
print(f"  Best Month:         {peak_m['month']} (N{peak_m['revenue']:,.0f} revenue)")
print(f"  Top Product:        {top_prod['product_name']} (N{top_prod['total_revenue']:,.0f})")
print(f"  Dominant Payment:   {top_pay['payment_method']} ({top_pay['transactions']} transactions)")
print(f"\nRECOMMENDATIONS:")
print(f"  1. Stock up Beverages & Grains in Oct-Dec -- festive season drives ~50% more demand")
print(f"  2. Limit 10% discounts -- they cut margins significantly vs undiscounted sales")
print(f"  3. Promote POS/Transfer to reduce cash handling risk (currently {cash_pct}% cash)")
print(f"  4. Fast movers (Indomie, Maggi, Gala) need buffer stock on Fridays-Sundays")
print("=" * 60)